import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./static/css/tailwind.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-mode="dark"  data-sidebar="dark" data-topbar="dark" className="dark group scroll-smooth" data-theme="dark" lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-base bg-body-bg text-body font-public dark:text-zink-100 dark:bg-zink-800 group-data-[skin=bordered]:bg-body-bordered group-data-[skin=bordered]:dark:bg-zink-700`}
      >
          {children}
      </body>
    </html>
  );
}
